### ISSUE TITLE
Installation hint [h2o-pysparkling] doesn't work

### ISSUE THREAD

**Issue by sbunzel** [mercury-ml-team/mercury-ml#2]
The installation hint [h2o-pysparkling] doesn't work due to the erroneous reference to the sparkling water package as `h2o-pysparkling`.

I can see that the guidelines on using these hints was recently removed from the readme. My suggestion would be to fix the h2o-pysparkling hint to install `pyspark==2.4` and `h2o-pysparkling-2.4` and explain this in the readme. Or else, just don't offer that extra installation hint.

**Comment by karlschriek** [comment]
The installation hints have actually all be removed as they don't work as intended. But it is worth pointing out in the readme how h2o-pysparkling should be installed
