### ISSUE TITLE
Develop MongoDB artifact storage

### ISSUE THREAD

**Issue by karlschriek** [mercury-ml-team/mercury-ml#7]
For JSON-type artifacts, it makes sense to create an implementation for document store such as MongoDB to serve as the remote store.

@aslisabanci?

**Comment by aslisabanci** [comment]
Yes, my implementation is on its way!

With this enhancement, we will have the option to store:

- session
- config
- metrics 

dictionaries under a flexibly configurated MongoDB collection, where the `document` can be queried by `model_id`.

-
